SQLALCHEMY_DATABASE_URI = 'mysql://root:111111@127.0.0.1/modog'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_MODIFICATIONS = True
SQLALCHEMY_ECHO = False
SQLALCHEMY_ENCODING = 'utf-8'
DEBUG = True
SERVERPORT = 9999